In [1]:
import torch
from torch import nn
# from loss import CustomBinFocalLoss

In [7]:
a = torch.rand((3, 1, 2, 2))
# element of a is between 0 and 1 including them
a

tensor([[[[0.8332, 0.3613],
          [0.4743, 0.0342]]],


        [[[0.9173, 0.0561],
          [0.3010, 0.2627]]],


        [[[0.2548, 0.8812],
          [0.2187, 0.5328]]]])

In [12]:
a[:, 0, 0, 0:2]

tensor([[0.8332, 0.3613],
        [0.9173, 0.0561],
        [0.2548, 0.8812]])

In [15]:
torch.pow(a, 2)

tensor([[[[0.6942, 0.1305],
          [0.2250, 0.0012]]],


        [[[0.8414, 0.0032],
          [0.0906, 0.0690]]],


        [[[0.0649, 0.7764],
          [0.0478, 0.2839]]]])

In [16]:
0.8332**2

0.6942222400000001

In [17]:
torch.mean(a)

tensor(0.4273)

In [18]:
from loss import BinConvLoss

In [ ]:
func = BinConvLoss()